import { Download, FileText, GraduationCap, LayoutDashboard, Receipt, UserRound } from 'lucide-react';
import { NavLink, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { useEffect, useState } from 'react';
import Header from '../components/Header';
import StatCard from '../components/StatCard';
import ResultsTable from '../components/ResultsTable';
import FeesCard from '../components/FeesCard';
import { api } from '../services/api';

function SectionHeading({ eyebrow, title, children }) { return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{children}</div>; }
function Profile({ student }) { const fields = [['Full name', student.fullName], ['Student ID', student.studentId], ['Email', student.email], ['Faculty', student.faculty], ['Program', student.program], ['Enrollment year', student.enrollmentYear]]; return <section className="profile-card"><div className="profile-intro"><div className="large-avatar">{student.fullName.split(' ').map(n => n[0]).join('')}</div><div><p className="eyebrow">STUDENT PROFILE</p><h3>{student.fullName}</h3><p>{student.program}</p></div></div><div className="profile-grid">{fields.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></section>; }
function Home({ student, results, fees }) { return <><div className="welcome-row"><div><p className="eyebrow">{student.semester} · 2026</p><h1>Welcome back, {student.fullName.split(' ')[0]} <span className="wave">👋</span></h1><p className="muted">Here’s a quick look at your academic journey.</p></div><div className="term-pill"><span className="term-dot" /> 2026 academic year</div></div><div className="stat-grid"><StatCard label="Current GPA" value={student.gpa} detail="Top 12% of your faculty" accent="mint" /><StatCard label="Total credits" value={student.credits} detail="12 credits in progress" accent="sand" /><StatCard label="Outstanding fees" value={`$${fees.outstanding}`} detail="Due Sep 30, 2026" accent="coral" /></div><div className="dashboard-grid"><div className="panel"><SectionHeading eyebrow="LATEST RESULTS" title="Your performance"><NavLink to="/student/results" className="text-link">View all results <span>↗</span></NavLink></SectionHeading><div className="result-highlight"><div className="ring"><strong>3.72</strong><span>GPA</span></div><div><strong>Looking good, Ahmed.</strong><p>Your results are trending above your faculty average this semester.</p></div></div><ResultsTable rows={results.slice(0, 3)} /></div><div className="panel deadline-panel"><SectionHeading eyebrow="FEES OVERVIEW" title="Stay on track"><NavLink to="/student/fees" className="text-link">View fees <span>↗</span></NavLink></SectionHeading><div className="fee-mini"><div className="fee-mini-head"><span>Paid this semester</span><strong>${fees.paid.toLocaleString()} <small>of ${fees.total.toLocaleString()}</small></strong></div><div className="progress-track"><div style={{ width: `${(fees.paid / fees.total) * 100}%` }} /></div><p><span className="dot coral" /> $450 outstanding · Due Sep 30</p></div><div className="next-card"><div className="next-icon"><Receipt size={19} /></div><div><span>NEXT UP</span><strong>Download your transcript</strong><p>Keep a copy for your records.</p></div><NavLink to="/student/transcript" aria-label="Open transcript">↗</NavLink></div></div></div><Profile student={student} /></>; }
function ResultsPage({ results }) { return <section className="content-section"><SectionHeading eyebrow="ACADEMIC RECORD" title="Results"><div className="gpa-badge"><span>Current GPA</span><strong>3.72</strong></div></SectionHeading><div className="full-panel"><ResultsTable rows={results} /></div></section>; }
function FeesPage({ fees }) { return <section className="content-section"><SectionHeading eyebrow="ACCOUNT SUMMARY" title="Fees"><p className="muted heading-note">Your payments and outstanding balance for the current academic year.</p></SectionHeading><FeesCard fees={fees} /></section>; }
function TranscriptPage({ student, transcript }) { const print = () => window.print(); return <section className="content-section transcript-page"><SectionHeading eyebrow="ACADEMIC RECORD" title="Transcript"><button className="outline-btn" onClick={print}><Download size={17} /> Download transcript</button></SectionHeading><div className="transcript-sheet"><div className="transcript-head"><div><span className="transcript-seal">H</span><div><strong>HORIZON UNIVERSITY</strong><span>OFFICIAL ACADEMIC TRANSCRIPT</span></div></div><span>Issued Sep 20, 2026</span></div><div className="transcript-info"><div><span>Student</span><strong>{student.fullName}</strong></div><div><span>Student ID</span><strong>{student.studentId}</strong></div><div><span>Program</span><strong>{student.program}</strong></div></div>{transcript.semesters.map(semester => <div className="semester-block" key={semester.name}><h3>{semester.name}</h3><ResultsTable rows={semester.courses} /></div>)}<div className="transcript-summary"><div><span>Total credits</span><strong>{student.credits}</strong></div><div><span>Cumulative GPA</span><strong>{student.gpa}</strong></div><div><span>Academic standing</span><strong className="standing">Good</strong></div></div></div></section>; }

export default function StudentDashboard({ student, onLogout }) { const [menuOpen, setMenuOpen] = useState(false); const [currentStudent, setCurrentStudent] = useState(student); const [data, setData] = useState({ results: [], fees: null, transcript: null }); const [error, setError] = useState(''); const location = useLocation(); const navigate = useNavigate(); useEffect(() => { Promise.all([api.getStudent(), api.getResults(), api.getFees(), api.getTranscript()]).then(([profile, resultData, fees, transcript]) => { setCurrentStudent({ ...profile, gpa: resultData.summary.gpa.toFixed(2), credits: String(resultData.summary.totalCredits) }); setData({ results: resultData.rows, fees, transcript }); }).catch((requestError) => { if (requestError.status === 401) return onLogout(); setError('Unable to load your information. Please try again later.'); }); }, [onLogout]); useEffect(() => { if (location.pathname === '/student') setMenuOpen(false); }, [location.pathname]); if (error) return <div className="loading-screen"><span>{error}</span><button className="text-link" onClick={() => window.location.reload()}>Try again</button></div>; if (!data.fees) return <div className="loading-screen"><div className="loader" /><span>Loading student information…</span></div>; return <div className="app-shell"><Header student={currentStudent} onLogout={onLogout} menuOpen={menuOpen} setMenuOpen={setMenuOpen} /><main className="main-content"><Routes><Route index element={<Home student={currentStudent} results={data.results} fees={data.fees} />} /><Route path="results" element={<ResultsPage results={data.results} />} /><Route path="fees" element={<FeesPage fees={data.fees} />} /><Route path="transcript" element={<TranscriptPage student={currentStudent} transcript={data.transcript} />} /><Route path="*" element={<button className="text-link" onClick={() => navigate('/student')}>Return to dashboard</button>} /></Routes></main><footer className="app-footer"><span>© 2026 Horizon University</span><span>Need help? <a href="mailto:registry@horizon.edu">Contact registry</a></span></footer></div>; }
